default_language_version:
  python: python3.10

default_stages: [commit]

repos:
#  - repo: https://github.com/asottile/reorder_python_imports
#    rev: v2.6.0
#    hooks:
#      - id: reorder-python-imports
#        args:
#          - --py38-plus

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: src/fpt/models/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pep8-naming==0.12.1
          - flake8-absolute-import==1.0
          - flake8-bugbear==21.11.29
          - flake8-builtins==1.5.3
          - flake8-class-attributes-order==0.1.2
          - flake8-cognitive-complexity==0.1.0
          - flake8-comprehensions==3.7.0
          - flake8-pytest-style==1.5.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: requirements-txt-fixer # order requirements alphabetically
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first # Check a common error of defining a docstring after code
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-yaml # Check yaml files
        args: ["--unsafe"]
      - id: end-of-file-fixer # Ensure that a file is either empty, or ends with one newline
        exclude: src/fpt/models/
      - id: mixed-line-ending # Replace or checks mixed line ending
        exclude: src/fpt/models/
      - id: trailing-whitespace # This hook trims trailing whitespace
        exclude: src/fpt/models/


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    - id: mypy
      args:
        - --python-version=3.10

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
